package trina.com.tvreviews;

import javax.annotation.Resource;

import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class ReviewPopulator implements CommandLineRunner {
	@Resource
	private ReviewRepository reviewRepo;

	@Resource
	private GenreRepository genreRepo;

	@Resource
	private TagRepository tagRepo;

	@Override
	public void run(String... args) throws Exception {
		// add genre and reviews

		Tag funny = new Tag("funny");
		tagRepo.save(funny);
		Tag family = new Tag("family");
		tagRepo.save(family);
		Tag parody = new Tag("parody");
		tagRepo.save(parody);
		Tag zany = new Tag("zany");
		tagRepo.save(zany);
		Tag lewd = new Tag("lewd");
		tagRepo.save(lewd);
		Tag friends = new Tag("friends");
		tagRepo.save(friends);
		Tag politics = new Tag("politics");
		tagRepo.save(politics);
		Tag adultery = new Tag("adultery");
		tagRepo.save(adultery);
		Tag music = new Tag("music");
		tagRepo.save(music);
		Tag singing = new Tag("singing");
		tagRepo.save(singing);
		Tag crime = new Tag("crime");
		tagRepo.save(crime);
		Tag ethics = new Tag("ethics");
		tagRepo.save(ethics);
		Tag law = new Tag("law");
		tagRepo.save(law);
		Tag men = new Tag("men");
		tagRepo.save(men);
		Tag women = new Tag("women");
		tagRepo.save(women);
		Tag drugs = new Tag("drugs");
		tagRepo.save(drugs);
		Tag prison = new Tag("prison");
		tagRepo.save(prison);

		Genre comedy = new Genre("Comedy");
		genreRepo.save(comedy);
		Review review1 = new Review(comedy, "Arrested Development",
				"Bacon ipsum dolor amet corned beef quis pig, mollit non exercitation frankfurter tongue pork belly t-bone consectetur pork loin bresaola anim shank. Nisi ham veniam ea, tri-tip pork belly boudin capicola ad flank hamburger. Adipisicing strip steak short loin, pork consectetur drumstick tenderloin beef laborum dolore pancetta nulla in cillum nostrud. Boudin dolore quis minim ut do. Leberkas turducken magna occaecat commodo. Id veniam swine quis nostrud, consectetur bresaola sunt irure incididunt consequat t-bone ribeye. Pork loin picanha mollit duis velit do labore corned beef adipisicing tri-tip filet mignon pig non doner. Commodo turkey laboris flank, ribeye drumstick kielbasa aliquip deserunt dolore proident incididunt enim lorem labore. Adipisicing incididunt venison frankfurter in dolore. Filet mignon pastrami enim, duis pork chop ut sirloin pork quis est fugiat ea velit magna. Do dolor officia sirloin in prosciutto.",
				"March 10, 2010",
				"Tenderloin filet mignon labore beef ribs shank chuck bacon ex meatloaf esse qui duis. Ball tip kielbasa sirloin andouille meatloaf chicken ex aute tail. Bresaola ground round irure do tenderloin swine. In burgdoggen ad magna, excepteur aliquip laborum id bacon quis jowl tenderloin. Pork chop exercitation mollit, ribeye quis t-bone nulla ut enim non in chuck cupidatat beef strip steak. Nostrud jowl cillum nulla, consectetur pancetta landjaeger sint duis capicola quis filet mignon. Beef ribs short ribs jerky kevin consectetur. Hamburger ad eiusmod eu non turkey kevin laboris ipsum porchetta chicken et pastrami. Proident consequat adipisicing short ribs est exercitation. Ullamco laboris kevin duis, in venison tongue ut. Biltong deserunt nisi t-bone ipsum id non boudin sunt pig meatball anim shoulder dolore short ribs. Reprehenderit spare ribs capicola chicken non..",
				"/images/Webp.net-resizeimagearrestdev2.jpg", family, funny);
		reviewRepo.save(review1);
		Review review2 = new Review(comedy, "Unbreakable Kimmy Schmidt",
				"Nostrud jowl cillum nulla, consectetur pancetta landjaeger sint duis capicola quis filet mignon. Beef ribs short ribs jerky kevin consectetur. Hamburger ad eiusmod eu non turkey kevin laboris ipsum porchetta chicken et pastrami. Proident consequat adipisicing short ribs est exercitation. Ullamco laboris kevin duis, in venison tongue ut. Biltong deserunt nisi t-bone ipsum id non boudin sunt pig meatball anim shoulder dolore short ribs. Reprehenderit spare ribs capicola chicken non. 	Corned beef ea kevin pork ut frankfurter. Occaecat nisi ullamco capicola swine. Nostrud strip steak spare ribs non landjaeger short ribs eiusmod brisket ham eu ex. Et strip steak ham hock kielbasa cupidatat. Ut burgdoggen venison, pastrami consequat in kevin cupidatat biltong excepteur nisi et picanha turkey. Aliquip ut chuck beef incididunt. Sint excepteur brisket ipsum cow, adipisicing frankfurter et burgdoggen culpa kielbasa tongue dolore.",
				"March 10, 2013",
				"Id veniam swine quis nostrud, consectetur bresaola sunt irure incididunt consequat t-bone ribeye. Pork loin picanha mollit duis velit do labore corned beef adipisicing tri-tip filet mignon pig non doner. Commodo turkey laboris flank, ribeye drumstick kielbasa aliquip deserunt dolore proident incididunt enim lorem labore. Adipisicing incididunt venison frankfurter in dolore. Filet mignon pastrami enim, duis pork chop ut sirloin pork quis est fugiat ea velit magna. Do dolor officia sirloin in prosciutto. Tenderloin filet mignon labore beef ribs shank chuck bacon ex meatloaf esse qui duis. Ball tip kielbasa sirloin andouille meatloaf chicken ex aute tail. Bresaola ground round irure do tenderloin swine. In burgdoggen ad magna, excepteur aliquip laborum id bacon quis jowl tenderloin. Pork chop exercitation mollit, ribeye quis t-bone nulla ut enim non in chuck cupidatat beef strip steak. Nostrud jowl cillum nulla, consectetur pancetta landjaeger sint duis capicola quis filet mignon. Beef ribs short ribs jerky kevin consectetur. Hamburger ad eiusmod eu non turkey kevin laboris ipsum porchetta chicken et pastrami. Proident consequat adipisicing short ribs est exercitation. Ullamco laboris kevin duis, in venison tongue ut. Biltong deserunt nisi t-bone ipsum id non boudin sunt pig meatball anim shoulder dolore short ribs. Reprehenderit spare ribs capicola chicken non.",
				"/images/Webp.net-resizeimagekimmy2.jpg", zany, funny, friends);
		reviewRepo.save(review2);
		Genre drama = new Genre("Drama");
		genreRepo.save(drama);
		Review review3 = new Review(drama, "Scandal",
				"Knock over christmas tree russian blue ask for petting cats go for world domination purr while eating lick butt. Have secret plans tuxedo cats always looking dapper, yet throw down all the stuff in the kitchen. Human is washing you why halp oh the horror flee scratch hiss bite chew on cable. Refuse to leave cardboard box and sometimes switches in french and say just because well why not so purr while eating climb leg, so meow to be let in. Fall asleep on the washing machine cat snacks. Going to catch the red dot today going to catch the red dot today. Fall asleep on the washing machine. Burrow under covers hunt by meowing loudly at 5am next to human slave food dispenser behind the couch. Missing until dinner time kitty loves pigs. Chase red laser dot. Chase ball of string munch on tasty moths sleep on dog bed, force dog to sleep on floor steal the warm chair right after you get up. Present belly, scratch hand when stroked purr. Purr when being pet lies down or meow meow, i tell my human ignore the squirrels, you'll never catch them anyway stare at ceiling. Get video posted to internet for chasing red dot howl on top of tall thing sleep in the bathroom sink yet swat at dog toy mouse squeak roll over. Have my breakfast spaghetti yarn cough furball have secret plans, or fall asleep on the washing machine or lick the plastic bag chase after silly colored fish toys around the house.",
				"March 10, 2014",
				"Roll over and sun my belly sit and stare. Nap all day if it fits, i sits. Eats owners hair then claws head please stop looking at your phone and pet me chase imaginary bugs, for eat prawns daintily with a claw then lick paws clean wash down prawns with a lap of carnation milk then retire to the warmest spot on the couch to claw at the fabric before taking a catnap. Poop on grasses. Eat grass, throw it back up tuxedo cats always looking dapper but with tail in the air, immediately regret falling into bathtub. Kitten is playing with dead mouse eat from dog's food. Thinking longingly about tuna brine chase after silly colored fish toys around the house and pee in human's bed until he cleans the litter box curl up and sleep on the freshly laundered towels cat is love, cat is life. Annoy owner until he gives you food say meow repeatedly until belly rubs, feels good proudly present butt to human, but scratch at fleas, meow until belly rubs, hide behind curtain when vacuum cleaner is on scratch strangers and poo on owners food. Cough hairball on conveniently placed pants pooping rainbow while flying in a toasted bread costume in space, or intently sniff hand, but attack dog, run away and pretend to be victim. Paw at beetle and eat it before it gets away leave fur on owners clothes bathe private parts with tongue then lick owner's face, sit by the fire intently stare at the same spot, yet pushes butt to face. Meow to be let out meow for food, then when human fills food dish, take a few bites of food and continue meowing cats making all the muffins where is my slave? I'm getting hungry and sweet beast. Plan steps for world domination stare at wall turn and meow stare at wall some more meow again continue staring . Jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water jumps off balcony gives owner dead mouse at present then poops in litter box snatches yarn and fights with dog cat chases laser then plays in grass finds tiny spot in cupboard and sleeps all day jumps in bathtub and meows when owner fills food dish the cat knocks over the food dish cat slides down the water slide and into pool and swims even though it does not like water but pooping rainbow while flying in a toasted bread costume in space sit in box sleep nap i cry and cry and cry unless you pet me, and then maybe i cry just for fun. Hiss and stare at nothing then run suddenly away put toy mouse in food bowl run out of litter box at full speed.",
				"/images/635902125679670664-1579496363_scandal2.png", lewd, politics, adultery);
		reviewRepo.save(review3);
		Genre reality = new Genre("Reality");
		genreRepo.save(reality);
		Review review4 = new Review(reality, "The Voice",
				"Cat is love, cat is life claws in your leg scamper throwup on your pillow, but hunt anything that moves. Scratch the box leave fur on owners clothes. Flee in terror at cucumber discovered on floor mesmerizing birds. Sit on human dream about hunting birds for purrrrrr yet chase laser munch on tasty moths, for chew iPad power cord. Jump around on couch, meow constantly until given food, licks paws drink water out of the faucet yet love to play with owner's hair tie i cry and cry and cry unless you pet me, and then maybe i cry just for fun so cats secretly make all the worlds muffins scream for no reason at 4 am. Eat and than sleep on your face knock dish off table head butt cant eat out of my own dish. Has closed eyes but still sees you ears back wide eyed find a way to fit in tiny box spit up on light gray carpet instead of adjacent linoleum. Stick butt in face with tail in the air and meow to be let out but scratch leg; meow for can opener to feed me, meowzer. Cat slap dog in face cough furball or fall over dead (not really but gets sypathy). Cough furball. Under the bed. Immediately regret falling into bathtub meow. White cat sleeps on a black shirt has closed eyes but still sees you flee in terror at cucumber discovered on floor. Find a way to fit in tiny box. Leave fur on owners clothes this human feeds me, i should be a god and pee in human's bed until he cleans the litter box but white cat sleeps on a black shirt i am the best. Chase ball of string you call this cat food and friends are not food for hunt by meowing loudly at 5am next to human slave food dispenser cats go for world domination stick butt in face, for asdflkjaertvlkjasntvkjn (sits on keyboard). Claws in your leg attack the dog then pretend like nothing happened roll on the floor purring your whiskers off meowing non stop for food. Be a nyan cat, feel great about it, be annoying 24/7 poop rainbows in litter box all day and sometimes switches in french and say miaou just because well why not. Climb leg. Gnaw the corn cob russian blue for mice this human feeds me, i should be a god and meow to be let in i am the best. Lie on your belly and purr when you are asleep you call this cat food but hack up furballs claw drapes. Milk the cow poop in litter box, scratch the walls licks your face so roll over and sun my belly hunt anything that moves, yet thinking longingly about tuna brine for munch on tasty moths.",

				"March 10, 2015",
				"Chase imaginary bugs sit by the fire yet tuxedo cats always looking dapper scratch me there, elevator butt. Eat a plant, kill a hand fooled again thinking the dog likes me, milk the cow spend all night ensuring people don't sleep sleep all day yet have my breakfast spaghetti yarn but spend all night ensuring people don't sleep sleep all day gnaw the corn cob. Meow immediately regret falling into bathtub yet under the bed. Cats go for world domination need to chase tail, for licks your face. Sit in window and stare oooh, a bird, yum i just saw other cats inside the house and nobody ask me before using my litter box yet need to chase tail always hungry i could pee on this if i had the energy small kitty warm kitty little balls of fur. Purr for no reason paw at beetle and eat it before it gets away yet small kitty warm kitty little balls of fur yet damn that dog . Lick arm hair purrr purr littel cat, little cat purr purr scratch leg; meow for can opener to feed me for gnaw the corn cob roll on the floor purring your whiskers off yet destroy the blinds a nice warm laptop for me to sit on. Sit on the laptop jump around on couch, meow constantly until given food, eat all the power cords eat all the power cords but scratch the furniture brown cats with pink ears. Scream at teh bath meowing non stop for food or pooping rainbow while flying in a toasted bread costume in space. Have my breakfast spaghetti yarn eat a plant, kill a hand scratch the postman wake up lick paw wake up owner meow meow. Hopped up on catnip hunt anything that moves, for love to play with owner's hair tie fall over dead (not really but gets sypathy) or sleep nap climb leg. Shake treat bag munch on tasty moths, and eat half my food and ask for more and lick the plastic bag. I cry and cry and cry unless you pet me, and then maybe i cry just for fun gnaw the corn cob but cat snacks my left donut is missing, as is my right. ",
				"/images/Webp.net-resizeimage-voicechairs.jpg", music, singing);
		reviewRepo.save(review4);
		Review review5 = new Review(reality, "Real Husbands of Hollywood",
				"Knowledge process outsourcing. Translating our vision of having a market leading platfrom goalposts or we need a paradigm shift, for let's unpack that later. Productize execute , nor market-facing, yet pixel pushing, but productize, yet screw the pooch. Are there any leftovers in the kitchen? ramp up, for time to open the kimono so no scraps hit the floor, yet can we take this offline, for can I just chime in on that one, for to be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders. It's a simple lift and shift job price point, or value prop. Feature creep ladder up / ladder back to the strategy but meeting assassin. Bench mark the last person we talked to said this would be ready so window-licker, so not the long pole in my tent I just wanted to give you a heads-up ultimate measure of success. We need to have a Come to Jesus meeting with Phil about his attitude organic growth, yet we need to dialog around your choice of work attire fire up your browser, high touch client nor design thinking game-plan. Digital literacy beef up, and touch base, nor knowledge process outsourcing or bottleneck mice we want to see more charts yet social currency. Close the loop what's the status on the deliverables for eow? cannibalize powerpoint Bunny, nor UX.",
				"March 10, 2015",
				"Feature creep overcome key issues to meet key milestones, put in in a deck for our standup today get buy-in quick-win put in in a deck for our standup today. Root-and-branch review win-win-win. Programmatically on your plate, for we need to future-proof this, for low-hanging fruit. It's a simple lift and shift job baseline overcome key issues to meet key milestones moving the goalposts. Game-plan cross functional teams enable out of the box brainstorming for streamline. Rock Star/Ninja. Out of the loop usabiltiy, for product management breakout fastworks get six alpha pups in here for a focus group we want to see more charts. Bench mark value-added are we in agreeance. I also believe it's important for every member to be involved and invested in our company and this is one way to do so are we in agreeance. Work vertical integration we need to have a Come to Jesus meeting with Phil about his attitude. Killing it horsehead offer, or bells and whistles, but i also believe it's important for every member to be involved and invested in our company and this is one way to do so turd polishing we've got to manage that low hanging fruit, product management breakout fastworks. You better eat a reality sandwich before you walk back in that boardroom organic growth cloud strategy nor shoot me an email show pony where the metal hits the meat. Idea shower data-point. Re-inventing the wheel. Push back win-win-win get all your ducks in a row market-facing granularity. Bells and whistles bench mark collaboration through advanced technlogy, but get buy-in core competencies not a hill to die on. Re-inventing the wheel in this space sacred cow what's the status on the deliverables for eow?. Best practices. I also believe it's important for every member to be involved and invested in our company and this is one way to do so. Please advise soonest make sure to include in your wheelhouse. ",
				"/images/Real-Husbands-of-Hollywood.jpg", parody, funny, men);
		reviewRepo.save(review5);
		Review review6 = new Review(drama, "Orange is the New Black",
				"Cupcake ipsum dolor sit amet biscuit tart. Tart cookie gummies liquorice sesame snaps tiramisu lemon drops. Sesame snaps bonbon lemon drops croissant oat cake gingerbread I love powder toffee. Caramels candy I love. Dragée chupa chups chocolate bar brownie. Dragée chocolate cake bonbon pie jelly-o donut I love. Tootsie roll chocolate cake I love chocolate bar bonbon sweet danish. Donut jelly beans muffin wafer bear claw muffin tiramisu danish lollipop. Powder icing I love wafer chocolate bar I love cheesecake candy canes biscuit. Jelly-o apple pie cheesecake sweet roll marshmallow donut. Chupa chups muffin danish oat cake toffee croissant. Macaroon I love chocolate cake marzipan pastry sesame snaps candy canes. Jelly cake sesame snaps jelly beans toffee topping cake icing. Croissant tart I love lollipop. Tart sweet chupa chups pie carrot cake candy canes. Toffee donut sugar plum sweet marzipan. Jujubes gummies cotton candy brownie liquorice brownie chocolate chocolate bar pudding. Jelly beans pie powder chocolate cake I love. Macaroon pudding topping tiramisu topping carrot cake jujubes. Brownie tiramisu jelly caramels topping lollipop jelly-o.",
				"March 10, 2015",
				"Topping I love halvah cake I love cake liquorice pudding. Carrot cake icing chocolate pastry sweet. Oat cake chupa chups I love sweet roll sugar plum muffin bonbon cake marzipan. Sugar plum cotton candy jelly-o I love halvah tiramisu muffin donut candy canes. Powder dessert sesame snaps gingerbread cookie cheesecake oat cake. Macaroon dragée sweet roll jelly beans muffin marzipan carrot cake croissant pudding. I love biscuit chupa chups. Marzipan chupa chups jelly. Caramels jelly-o caramels toffee chocolate cake gingerbread bear claw. Toffee apple pie pie. Jelly-o candy canes cotton candy I love. Icing muffin sweet bear claw soufflé I love cotton candy pudding. I love soufflé chupa chups lollipop dragée cake tootsie roll. Jelly cupcake sweet muffin. Cupcake jelly beans donut sugar plum topping. Pastry gummies muffin. Jelly-o pudding sesame snaps marzipan donut jelly beans.",
				"/images/ORANGE.png", crime, prison, women, drugs);
		reviewRepo.save(review6);
		Review review7 = new Review(drama, "Suits",
				"We need to leverage our synergies I have zero cycles for this curate, baseline the procedure and samepage your department productize we've got to manage that low hanging fruit. PowerPointless powerPointless accountable talk if you want to motivate these clowns, try less carrot and more stick, yet baseline the procedure and samepage your department drink the Kool-aid enough to wash your face. Closing these latest prospects is like putting socks on an octopus best practices, so knowledge is power. We're ahead of the curve on that one wheelhouse get buy-in collaboration through advanced technlogy and time to open the kimono. Window-licker back to the drawing-board proceduralize. Quick win value-added, so waste of resources, but get six alpha pups in here for a focus group drink from the firehose, nor back of the net overcome key issues to meet key milestones. Game plan product management breakout fastworks. Put a record on and see who dances. Going forward i don't want to drain the whole swamp, i just want to shoot some alligators can you ballpark the cost per unit for me, so we need to button up our approach, blue money. Win-win-win this is not the hill i want to die on, and drop-dead date, or Q1, or UX, nor drink from the firehose. Can we take this offline. Take five, punch the tree, and come back in here with a clear head. Going forward quick win we need to have a Come to Jesus meeting with Phil about his attitude. Personal development commitment to the cause and not a hill to die on. Golden goose. Design thinking hard stop we want to see more charts please advise soonest synergize productive mindfulness. We need to dialog around your choice of work attire staff engagement hammer out, value-added. Those options are already baked in with this model first-order optimal strategies for we just need to put these last issues to bed, so punter yet waste of resources.",
				"March 10, 2015",
				"Knowledge process outsourcing. Translating our vision of having a market leading platfrom goalposts or we need a paradigm shift, for let's unpack that later. Productize execute , nor market-facing, yet pixel pushing, but productize, yet screw the pooch. Are there any leftovers in the kitchen? ramp up, for time to open the kimono so no scraps hit the floor, yet can we take this offline, for can I just chime in on that one, for to be inspired is to become creative, innovative and energized we want this philosophy to trickle down to all our stakeholders. It's a simple lift and shift job price point, or value prop. Feature creep ladder up / ladder back to the strategy but meeting assassin. Bench mark the last person we talked to said this would be ready so window-licker, so not the long pole in my tent I just wanted to give you a heads-up ultimate measure of success. We need to have a Come to Jesus meeting with Phil about his attitude organic growth, yet we need to dialog around your choice of work attire fire up your browser, high touch client nor design thinking game-plan. Digital literacy beef up, and touch base, nor knowledge process outsourcing or bottleneck mice we want to see more charts yet social currency. Close the loop what's the status on the deliverables for eow? cannibalize powerpoint Bunny, nor UX.",
				"/images/Suits.jpg", law, ethics, crime);
		reviewRepo.save(review7);

	}

}
